# Generated by Django 6.0.6 on 2026-06-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="precio",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
