# Generated by Django 6.0.6 on 2026-06-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relaciones", "0002_producto_precio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cursos", models.ManyToManyField(to="relaciones.curso")),
            ],
        ),
    ]
